# Generated by Django 3.0.4 on 2020-04-26 04:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0009_auto_20200426_0129'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentativa',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='tentativa',
            name='nivel',
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nivel', models.CharField(choices=[(0, 'Nenhum'), (1, '1 - Lembrar'), (2, '2 - Entender'), (3, '3 - Aplicar'), (4, '4 - Analisar'), (5, '5 - Avaliar'), (6, '6 - Criar')], default=0, max_length=50)),
                ('bloqueado', models.BooleanField(default=True, verbose_name='bloquear')),
                ('modulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='progame.Modulo')),
            ],
        ),
        migrations.AddField(
            model_name='tentativa',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentativas', to='quiz.Quiz'),
        ),
    ]
