# Generated by Django 3.0.4 on 2020-05-01 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200430_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tentativa',
            options={'verbose_name': 'tentativa', 'verbose_name_plural': 'tentativas'},
        ),
    ]
