# Generated by Django 3.0.4 on 2020-05-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200502_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='bloqueado',
            field=models.BooleanField(default=False, verbose_name='bloquear'),
        ),
    ]
