# Generated by Django 3.0.4 on 2020-06-02 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200531_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'quizzes'},
        ),
        migrations.AlterModelOptions(
            name='tentativa',
            options={},
        ),
    ]
