# Generated by Django 3.0.4 on 2020-06-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0020_auto_20200607_2117'),
        ('quiz', '0009_auto_20200601_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questoes',
            field=models.ManyToManyField(related_name='quizzes', to='progame.Questao'),
        ),
    ]
