# Generated by Django 3.0.4 on 2020-07-31 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0028_itemconquista_descricao2'),
        ('quiz', '0010_quiz_questoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='modulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='progame.Modulo'),
        ),
        migrations.AlterField(
            model_name='tentativa',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='quiz.Quiz'),
        ),
    ]
