# Generated by Django 3.0.4 on 2020-04-01 00:22

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ausers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('is_correta', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=255, verbose_name='nome do módulo')),
                ('descricao', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentenca', models.CharField(max_length=500, verbose_name='sentença')),
                ('descricao', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='descrição da questão')),
                ('nivel', models.CharField(choices=[(1, '1 - Lembrar'), (2, '2 - Entender'), (3, '3 - Aplicar'), (4, '4 - Analisar'), (5, '5 - Avaliar'), (6, '6 - Criar')], max_length=50, null=True, verbose_name='nível')),
                ('modulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes', to='progame.Modulo')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=255, verbose_name='nome da turma')),
                ('secao', models.CharField(blank=True, max_length=100, null=True, verbose_name='seção')),
                ('sala', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('codigo', models.CharField(editable=False, max_length=10, null=True, unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='turmas')),
                ('alunos', models.ManyToManyField(blank=True, to='ausers.Aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='ausers.Professor')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField(auto_now_add=True)),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas_alternativa', to='progame.Alternativa')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas_aluno', to='ausers.Aluno')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas_questao', to='progame.Questao')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
        migrations.AddField(
            model_name='modulo',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='progame.Turma'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='progame.Questao'),
        ),
    ]
