# Generated by Django 3.0.4 on 2020-04-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausers', '0002_auto_20200402_0253'),
        ('progame', '0006_resposta_pontos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NivelAlunoModulo',
            new_name='StatsAlunoModulo',
        ),
        migrations.RenameModel(
            old_name='NivelAlunoTurma',
            new_name='StatsAlunoTurma',
        ),
        migrations.RenameField(
            model_name='resposta',
            old_name='pontos',
            new_name='pontos_acerto',
        ),
        migrations.AddField(
            model_name='resposta',
            name='pontos_tempo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
