# Generated by Django 3.0.4 on 2020-04-23 01:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0007_auto_20200416_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='descricao',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=130, null=True, verbose_name='descrição'),
        ),
    ]
