# Generated by Django 3.0.4 on 2020-04-26 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0008_auto_20200422_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resposta',
            old_name='pontos_acerto',
            new_name='pontos',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='pontos_tempo',
        ),
    ]
