# Generated by Django 3.0.4 on 2020-04-26 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200426_0129'),
        ('progame', '0009_auto_20200426_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='quiz',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes', to='quiz.Quiz'),
        ),
    ]
