# Generated by Django 3.0.4 on 2020-04-26 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0010_questao_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemConquista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item_conquista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas_alunos', to='progame.ItemConquista')),
            ],
        ),
    ]
