# Generated by Django 3.0.4 on 2020-04-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0011_conquista_itemconquista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='hora_fim',
            field=models.TimeField(),
        ),
    ]
