# Generated by Django 3.0.4 on 2020-05-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0012_auto_20200429_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='descricao',
            field=models.TextField(blank=True, max_length=130, null=True, verbose_name='descrição'),
        ),
    ]
