# Generated by Django 3.0.4 on 2020-05-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0014_auto_20200509_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='conquista',
            name='visualizado',
            field=models.BooleanField(default=False),
        ),
    ]
