# Generated by Django 3.0.4 on 2020-05-29 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ausers', '0005_professor_uuid'),
        ('progame', '0015_conquista_visualizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='alternativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_alternativa', to='progame.Alternativa'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_aluno', to='ausers.Aluno'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_questao', to='progame.Questao'),
        ),
    ]
