# Generated by Django 3.0.4 on 2020-05-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0016_auto_20200529_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='verbo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='nome do módulo'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='nivel',
            field=models.CharField(choices=[(0, 'Nenhum'), (1, '1 - Lembrar'), (2, '2 - Entender'), (3, '3 - Aplicar'), (4, '4 - Analisar'), (5, '5 - Avaliar'), (6, '6 - Criar')], max_length=1, null=True, verbose_name='nível'),
        ),
        migrations.AlterField(
            model_name='statsalunomodulo',
            name='nivel',
            field=models.CharField(choices=[(0, 'Nenhum'), (1, '1 - Lembrar'), (2, '2 - Entender'), (3, '3 - Aplicar'), (4, '4 - Analisar'), (5, '5 - Avaliar'), (6, '6 - Criar')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='statsalunoturma',
            name='nivel',
            field=models.CharField(choices=[(0, 'Nenhum'), (1, '1 - Lembrar'), (2, '2 - Entender'), (3, '3 - Aplicar'), (4, '4 - Analisar'), (5, '5 - Avaliar'), (6, '6 - Criar')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.CharField(editable=False, max_length=6, null=True, unique=True),
        ),
    ]
