# Generated by Django 3.0.4 on 2020-06-02 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0017_auto_20200531_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveSmallIntegerField()),
                ('nome', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'nível',
                'verbose_name_plural': 'níveis',
            },
        ),
        migrations.CreateModel(
            name='Verbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=20)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verbos', to='progame.Nivel')),
            ],
        ),
        migrations.AlterField(
            model_name='questao',
            name='verbo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='progame.Verbo'),
        ),
    ]
