# Generated by Django 3.0.4 on 2020-06-02 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0018_auto_20200601_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemconquista',
            options={'verbose_name_plural': 'itens conquista'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'verbose_name': 'módulo', 'verbose_name_plural': 'módulos'},
        ),
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name': 'questão', 'verbose_name_plural': 'questões'},
        ),
        migrations.AlterModelOptions(
            name='resposta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={},
        ),
        migrations.DeleteModel(
            name='StatsAlunoTurma',
        ),
    ]
