# Generated by Django 3.0.4 on 2020-06-08 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200601_2315'),
        ('ausers', '0006_auto_20200601_2315'),
        ('progame', '0019_auto_20200601_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='ausers.Professor'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='quiz',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_questoes', to='quiz.Quiz'),
        ),
    ]
