# Generated by Django 3.0.4 on 2020-06-08 00:48

from django.db import migrations


def change_questoes_location(apps, schema_editor):
    Quiz = apps.get_model('quiz', 'Quiz')
    Questao = apps.get_model('progame', 'Questao')

    for questao in Questao.objects.all():
        quiz = Quiz.objects.get(pk=questao.quiz.pk)
        quiz.questoes.add(questao)
        quiz.save()


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0020_auto_20200607_2117'),
    ]

    operations = [
        migrations.RunPython(change_questoes_location)
    ]
