# Generated by Django 3.0.4 on 2020-06-08 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0023_auto_20200607_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='quiz',
        ),
    ]
