# Generated by Django 3.0.4 on 2020-06-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0024_remove_questao_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbo',
            name='verbo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verbo',
            name='palavra',
            field=models.CharField(max_length=50),
        ),
    ]
