# Generated by Django 3.0.4 on 2020-07-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0025_auto_20200609_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='nome',
            field=models.TextField(max_length=700),
        ),
    ]
