# Generated by Django 3.0.4 on 2020-07-31 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0028_itemconquista_descricao2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conquista',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conquistas', to='progame.Turma'),
        ),
    ]
