# Generated by Django 3.0.4 on 2020-08-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0029_auto_20200731_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='discord',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
