# Generated by Django 3.0.4 on 2020-08-04 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0030_auto_20200802_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='tempo_para_responder',
            field=models.DurationField(default=datetime.timedelta(seconds=60)),
        ),
    ]
