# Generated by Django 3.0.4 on 2020-04-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progame', '0011_conquista_itemconquista'),
        ('ausers', '0002_auto_20200402_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='conquistas',
            field=models.ManyToManyField(to='progame.Conquista'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turmas_favoritas',
            field=models.ManyToManyField(to='progame.Turma'),
        ),
    ]
