# Generated by Django 3.0.4 on 2020-05-09 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ausers', '0003_auto_20200426_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='conquistas',
        ),
    ]
