# Generated by Django 3.0.4 on 2020-05-16 22:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ausers', '0004_remove_aluno_conquistas'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
