# Generated by Django 3.0.4 on 2020-07-30 02:17
import uuid

from django.db import migrations


def create_aluno_uuid(apps, schema_editor):
    Aluno = apps.get_model('ausers', 'Aluno')

    for aluno in Aluno.objects.all():
        aluno.uuid = uuid.uuid4()
        aluno.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ausers', '0007_aluno_uuid'),
    ]

    operations = [
        migrations.RunPython(create_aluno_uuid)
    ]
