# Generated by Django 3.0.4 on 2020-07-30 03:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ausers', '0008_auto_20200729_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
